- hosts: DB_worshop-1, DB_worshop-2
  remote_user: ubuntu
  become: true

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        name: "*"
        state: latest

    - name: Install dependencies
      apt:
        pkg:
          - ca-certificates 
          - curl
          - gnupg2
          - lsb-release
          - htop
    
    - name: Add repository - Percona
      apt:
        deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"

    - name: Setup Persona MySQL distro
      shell: percona-release setup ps80

    - name: Install MySQL 8 from Percona
      apt: name=percona-server-server state=present update_cache=yes

    - name: Copy configuration
      template:
        src: templates/mysqld.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644
        
    - name: Restart DB service to apply configuration
      systemd:
        name: mysql
        state: restarted